provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  hello:
    lang: python3
    handler: ./hello
    image: hello:0.1
  middleware:
    lang: golang-middleware
    handler: ./middleware
    image: middleware:0.1
    
    
    
    
    
    
    
    
